### ISSUE TITLE
Minor suggestions for the documentation

### ISSUE THREAD

**Issue by malmans2** [sam-greenwood/taco_vis#18]
A few minor suggestions @sam-greenwood:

- [x]  You have both README.md and README.rst. I think you can get rid of README.md at this point, so you just have to edit one.
- [x]  I think something is not right in [README.md](https://github.com/sam-greenwood/taco_vis/blob/master/README.md) (and in the figure shown [here](https://taco-vis.readthedocs.io/en/latest/index.html#torsional-axisymmetric-core-oscillations-visualiser-taco-vis)). At the very beginning you mention that the dataset is generated with `data = np.random.rand(10,10)`, but then there are negative values and the colorbar shows values above 1 and below -1. I would expect a plot similar to the plot you have [here](https://taco-vis.readthedocs.io/en/latest/examples/random.html#sphx-glr-examples-random-py).
- [x]  What about double backquotes for the installation command [here](https://taco-vis.readthedocs.io/en/latest/README.html#installation)? ``` ``python setup.py install`` ``` 
- [x]  Add an empty line before ``.. code-block:`` [here](https://taco-vis.readthedocs.io/en/latest/README.html#known-issues)
- [x]  I don't think you need both of these sections: [Examples](https://taco-vis.readthedocs.io/en/latest/README.html#examples) and  [Example gallery](https://taco-vis.readthedocs.io/en/latest/examples/index.html#example-gallery) . I would combine them.
- [x]  I would quickly explain how to test the package locally. Maybe in the [Installation](https://taco-vis.readthedocs.io/en/latest/README.html#installation) section?
- [x]  In the example that uses Cox et al., what about adding a doi/link to the paper?

per openjournals/joss-reviews#1720

**Comment by sam-greenwood** [comment]
Thanks for the ideas, I've implemented all of your changes

**Comment by malmans2** [comment]
Is the front page shown in the documentation automatically generated based on [README.md](https://github.com/sam-greenwood/taco_vis/blob/master/README.md), or does it point to a separate file? I see a [README.rst](https://github.com/sam-greenwood/taco_vis/blob/master/docs/source/README.rst) in the doc folder. I'll leave it up to you whether to have just a single or multiple READMEs, but make sure they are consistent. For example, the first figure in README.md points the plot with negative values, but you use `np.random.rand` in the code to reproduce it.
Other than that, everything looks good!

**Comment by sam-greenwood** [comment]
The data plotted are all in the positive colours on the colour scale (since it was generated with `np.random.rand` as you say). The code always produces a colour scale centered on 0. This decision was taken since with torsional waves you would always expect to see both negative and positive values.

**Comment by malmans2** [comment]
This is the figure in the README. https://github.com/sam-greenwood/taco_vis/blob/master/paper/images/example_cylinders_3D.png 
Are you sure these values are all positive? Maybe it's just my eyes, but I see light blue while zero is set at green. Or maybe I'm missing something.

**Comment by sam-greenwood** [comment]
Fixed that now, it was showing up for me but maybe I messed up committing it correctly. Thanks for spotting that.

**Comment by malmans2** [comment]
Cool! I'm going to close this.
