### ISSUE TITLE
Proper name in LICENSE

### ISSUE THREAD

**Issue by banesullivan** [sam-greenwood/taco_vis#2]
https://github.com/sam-greenwood/taco_vis/blob/1a8ee79fb5475f84b50dcaa68ffac29b7bb22d80/LICENSE#L3

Could you please make sure the license properly list your name, not GitHub account?

per https://github.com/openjournals/joss-reviews/issues/1720

**Comment by sam-greenwood** [comment]
Changed to Sam Greenwood

**Comment by banesullivan** [comment]
thanks!
