### ISSUE TITLE
Documentation and Examples

### ISSUE THREAD

**Issue by banesullivan** [sam-greenwood/taco_vis#3]
Is there work towards building a documentation site (possibly hosted on Read the Docs) that outlines the project, contains full API documentation, and provides reproducible, real-world examples?

per https://github.com/openjournals/joss-reviews/issues/1720

**Comment by malmans2** [comment]
I was about to open the exact same issue!

**Comment by sam-greenwood** [comment]
Given that the user need only interact with the code with a few functions, I had originally intended and have tried to write the readme to cover the full usage of package. Do you feel this information would be better served on a separate documentation site or would it be fine in the readme (or both)?

**Comment by banesullivan** [comment]
I think a separate site would be best... that way you can have the examples run and be tested automatically. I think this issue goes hand-in-hand with #8.

Examples and docs in READMEs often go untested and become outdated really quickly. Having something like a sphinx-gallery ensures that when a new user copy/pastes code from your example, it'll simply work.

**Comment by sam-greenwood** [comment]
Ok, thanks for the work getting me started with the sphinx gallery, not something I've heard of before but looks useful!

**Comment by sam-greenwood** [comment]
Ok created the documentation with sphinx.

**Comment by banesullivan** [comment]
@sam-greenwood, is the documentation automatically being built and deployed anywhere - such as on [readthedocs.org](https://readthedocs.org)?

**Comment by sam-greenwood** [comment]
> @sam-greenwood, is the documentation automatically being built and deployed anywhere - such as on [readthedocs.org](https://readthedocs.org)?

I have tried to host it on readthedocs, but it's now error-ing whilst building the sphinx gallery, which I cannot reproduce locally. I have tried cloning the repo and using the same version of sphinx as readthedocs has used (1.8.5) which works on my local machine. Any suggestions of how I might resolve this?

https://readthedocs.org/projects/taco-vis/builds/10202526/

**Comment by banesullivan** [comment]
#15 should fix that issue! Let me know when you get it deployed on readthedocs! 🚀

**Comment by sam-greenwood** [comment]
> #15 should fix that issue! Let me know when you get it deployed on readthedocs! 🚀

All fixed now, thanks!

**Comment by banesullivan** [comment]
Since the docs are live, I'll close this now!
